#! /bin/bash -x
param_count="$#"
if [[ param_count -eq 0 ]]; then
    find . -maxdepth 1 -type f 2> /dev/null | wc -l
elif [[ param_count -eq 1 ]]; then
    if [ "$1" == "-h" ]; then
        printf "%s\n%s\n" "filecnt <dir_name> [-h]" "Counts all usual files within <dir_name>"
    elif [ ! -d "$1" ]; then
        echo "\"$1\": no such directory"
        exit 1
    else
        find "$1" -maxdepth 1 -type f 2> /dev/null | wc -l
    fi
else
    echo "Illegal parameters count"
    printf "%s\n%s\n" "filecnt <dir_name> [-h]" "Counts all usual files within <dir_name>"
fi
